// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxrzkvpkmnxwlztsphho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cnprdnBrbW54d2x6dHNwaGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTQ5NDEsImV4cCI6MjA2NjI3MDk0MX0.1eskw262GueHv3Ei9XK5mcQ53gxmY7PdJSzEHf3Q58k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);